spring.application.name=MovieDemo

spring.datasource.url=jdbc:mysql://localhost:3306/moviedb
spring.datasource.username=root
spring.datasource.password=Praveen@12
spring.jpa.hibernate.ddl-auto=update

